name: create_automated_tags

on:
  push:
    branches: [ main ]

jobs:
  tagging:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------------------------------------
      # Checkout the branch from the github repository that triggered the action
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      # ------------------------------------------------------------------------

      # --------------------------
      # Setup a python environment
      - name: Setup python
        uses: "actions/setup-python@v2"
        with:
          python-version: '3.9'
      # --------------------------

      - name: Create new tag based on version.py
        run: git tag $(cut -d' ' -f3 version.py | sed 's/"//g')

